### ISSUE TITLE
上传登录序列接口部分异常

### ISSUE THREAD

**Issue by Jane151013** [h4rdy/Acunetix11-API-Documentation#1]
你好，首先感谢您分享了如此详细深入而又宝贵的文档给我们学习参考，受益良多。
在根据您提供的文档进行操作的过程中，我发现上传登录序列部分执行了文档描述的两步操作之后虽然没有报错，但AWVS的后台数据库里也并没有新增相关的配置（如果在页面执行同样的操作，结果会被保存在数据库的target_configuration表中）
然后我在执行页面操作的时候通过F12抓包发现上传登陆序列的配置其实有三步，除了您文档描述的两步以外还有个PATCH的请求操作，url为/api/v1/targets/{target_id}/configuration，与您文档的网站登录设置一致。所以当我执行完之前的两步之后再执行这步时，如果请求参数如果只发送{\"login\":{\"kind\": \"sequence\"}}"会报login sequence not found，数据库中的内容依旧没有变化。
所以希望您可以帮忙解答一下这个问题，不胜感激

**Comment by h4rdy** [comment]
我修改了关于上传登录序列的接口文档。感谢你的提醒,上传的确需要三步,主要问题在于第二步上传文件的过程中,需要增加对应的header头及cookie，详情见更新后的文档。其中有个坑需要注意下,如果使用的python,并且lsr文件中包含了中文,那么在post的时候可能会存在编码相关的问题。并且我建议扫描设置是使用添加cookie的方式进行扫描，而不使用登录序列。如果在登录过程中需要验证码,那么利用登录序列是无法登录成功的。

**Comment by Jane151013** [comment]
很惊喜一大早就收到了您的回复，并且很感谢您的悉心解答
但我依旧有个问题，cookie其实是在AWVS的页面操作时才会生成的，那么调用API的时候如何获取Cookie呢？
另外，我尝试了通过页面获取cookie然后放到上传登录凭证的报文headers里面，结果在第三步的时候依旧报错login sequence not found

**Comment by h4rdy** [comment]
感觉你的反馈,我再次更新了上传接口的文档。新的接口文档不需要cookie。

**Comment by h4rdy** [comment]
你可以先测试,去掉lsr文件中的中文,看能否成功上传并保存，以确保不是中文编码的问题。

**Comment by Jane151013** [comment]
谢谢你的提示，我把登陆序列里的中文都删掉了，重新设置了各步骤请求里的文件大小，上传终于成功了。非常感谢
