### ISSUE TITLE
上传登陆序列文件格式异常的问题

### ISSUE THREAD

**Issue by Jane151013** [h4rdy/Acunetix11-API-Documentation#2]
你好，我又一次冒昧打扰了。。。根据您的指点，不带中文的登录序列上传是没有问题的了。通过页面和API上传的登录序列文件在C:\ProgramData\Acunetix 11\shared\targets保存的文件格式均为utf-8，但如果登录序列包含中文，则会报错UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 274: invalid start byte。由于我的登陆序列不能避免中文，所以想请问一下如何解决这个问题
另外加一句，我在上传登录序列的第二步时候，得到的响应就是204，但实际上后台是有报错的，所以204应该并不能表明上传成功

**Comment by h4rdy** [comment]
这个问题当时我也遇到过了，后来一直也没能解决。我用的python3

**Comment by Jane151013** [comment]
奋斗了好几天，竟然解决了，一开始用的接口测试工具curl发的请求。为了指定中文的编码格式，换了LR，把整个登陆序列都用utf8转码，发过去就没有报错了，扫描结果也和页面上传的扫描结果一致，问题解决。
