### ISSUE TITLE
运行报错了

### ISSUE THREAD

**Issue by jiangsi520** [h4rdy/Acunetix11-API-Documentation#5]
![image](https://user-images.githubusercontent.com/30169495/48056904-b978ca80-e1ed-11e8-97f3-7808d8dd464c.png)

运行报错了,另外token,url,这里需要填什么？是环境地址还是自己的url？

**Comment by h4rdy** [comment]
1. 运行报错了, 看错误异常是你没有定义"error"。
2. url填搭建AWVS的地址。
3. 没有token这个参数。
